### ISSUE TITLE
Queueing different jobs - wait for completion

### ISSUE THREAD

**Issue by MadsBen** [djmaze/resticker#104]
I have resticker running in 3 different containers, like in the example:
https://github.com/djmaze/resticker/blob/master/docker-compose.example.yml

The backup repository is hosted by Backblaze B2. But, my upload speed is slow (and unpredictable), so the the jobs might not be finished, before the next job is scheduled to begin.

Example:
Backup job runs everyday at 02:00 .
Prune job is scheduled to run once a week, Sunday at 16:00. But, if backup job is not finished, prune job will failed and will have to wait a week, until next try, where the same scenario might happen and prune will never run.
Likewise, prune and check jobs might take longer than expected to run, if there is errors in the repository.

It would be great, if it was possible for the jobs to wait for the previous job was complete and then begin, when the lock on the repository is removed.

**Comment by djmaze** [comment]
Mhh, interesting proposal. But I guess the best way would be to not retry the job forever if the repo is locked, but only a few times. Maybe with an exponential back-off. If it still fails 3 times in a row or so, it could finally report an error.

**Comment by MadsBen** [comment]
If the back-off is a variable, then it is a possibility.

Or perhaps it could be done with the pre- and post commands. Setting a keyword in a file to monitor for (locked / unlocked). But still need a routine in the commands to repeatedly check the file.
