### ISSUE TITLE
Implement POST_COMMAND_INCOMPLETE?

### ISSUE THREAD

**Issue by MadsBen** [djmaze/resticker#107]
Restic has 3 exit status codes:

- 0 when the backup was successful (snapshot with all source files created)
- 1 when there was a fatal error (no snapshot created)
- 3 when some source files could not be read (incomplete snapshot with remaining files created)

Code 1 and 3 both results in POST_COMMANDS_FAILURE to be executed, which is a bit misleading, since code 3 is not a failure.
An additional POST_COMMANDS_ option would be nice, to cover code 3.

Here's an example from the log, where there is a warning, but no failure, but it executes the POST_COMMANDS_FAILURE:

```
snapshot 7dd83929 saved
Warning: at least one source file could not be read
curl -X POST --data "{\"title\": \"Backup failed!\", \"body\": \"Backup failed. Go fix!\"}" http://restic_notify:5000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    61    0     0  100    61      0     43  0:00:01  0:00:01 --:--:--    43
100    63  100     2  100    61      1     31  0:00:02  0:00:01  0:00:01    32
ok
(0x51cae0,0x5a2fd8)
Stopping
Waiting
Exiting
```

**Comment by djmaze** [comment]
@MadsBen That is an interesting point. I was not aware of that.

Makes total sense to have a separate command for those "non-fatal" errors. I could totally make use of that! Will try to implement this.

**Comment by MadsBen** [comment]
I still think this is relevant.

**Comment by MadsBen** [comment]
Just want to add, that it works. Great job.
