### ISSUE TITLE
use of RESTIC_PASSWORD env variable

### ISSUE THREAD

**Issue by bread-wolf** [djmaze/resticker#111]
Hi,

I am not sure if that environment variable is still meant to be set, it doesn't seem like the entry point script actually initializes the repository anymore like the documentation indicates unless I missed something.

That means we have to manually initialize the repository before running the container right?

I think an auto-initialization makes sense and is quite convenient, and using a secret to store the password should be safe enough (restic even supports that by default).

Thanks for your answers.

**Comment by djmaze** [comment]
@bread-wolf The repository is still initialized automatically in the entrypoint script (unless you call the `unlock` command).

(Sorry for the late response! See #129)
