### ISSUE TITLE
restic 0.13.0

### ISSUE THREAD

**Issue by MadsBen** [djmaze/resticker#128]
Please upgrade restic to version 0.13.0

**Comment by thueske** [comment]
See: https://github.com/djmaze/resticker/pull/127

**Comment by matt-laird** [comment]
There was a bug fix, released 2 days ago - 0.13.1 - https://github.com/restic/restic/releases/tag/v0.13.1

**Comment by matt-laird** [comment]
For those who want an interim "fix" you can in-place upgrade restic internally if you can run `restic self-update`

**Comment by djmaze** [comment]
Thanks, updated pr in #130

**Comment by djmaze** [comment]
And.. Sorry for the waiting!
