### ISSUE TITLE
Big memory usage

### ISSUE THREAD

**Issue by e-belair** [djmaze/resticker#137]
I have resticker container up for 3 weeks now and I noticed that the memory usage is huge:
![image](https://user-images.githubusercontent.com/596562/175381707-1ac56668-3be9-4642-a9f4-333508ad7375.png)
Do you have an idea of what could consume so much memory?

**Comment by djmaze** [comment]
@e-belair Can you the following command in order to show which command is taking up the memory in the container?

```bash
docker top <CONTAINER ID> u
```

**Comment by e-belair** [comment]
Here is the result of the commands and it's a bit confusing:
```
$ docker stat resticker
CONTAINER ID   NAME        CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O         PIDS
de432d541be0   resticker   0.00%     73.68GiB / 187.6GiB   39.28%    228kB / 1.15MB   18.9TB / 3.21TB   8

$ docker top de432d541be0 u
USER                PID                 %CPU                %MEM                VSZ                 RSS                 TTY                 STAT                START               TIME                COMMAND
root                41650               0.0                 0.0                 703840              8456                ?                   Ssl                 May31               0:01                go-cron 0 0 0 * * * /usr/local/bin/backup
```

**Comment by e-belair** [comment]
I think I found my answer [here](https://serverfault.com/questions/735246/how-does-docker-stats-output-relate-to-top-output)

**Comment by ThomDietrich** [comment]
... which is? :)

**Comment by e-belair** [comment]
@ThomDietrich I'm still investigating but I'm pretty sure it's due to the file cache memory.
(I closed the ticket because it's a docker issue, not resticker)
