### ISSUE TITLE
Which docker tag to use?

### ISSUE THREAD

**Issue by dodedodo** [djmaze/resticker#149]
Hey 👋

I'm trying to determine which version of resticker to use, but I'm stumbling on these issues:
- the `:latest` docker tag does not match any other images (looking at the sha-sums) and is also not the newest image. This has been raised before in #24 
- Are the `:pr-xxx` tags official releases? Or rather for development / testing?
- There seem to be some [changes since v1.6.0](https://github.com/djmaze/resticker/compare/1.6.0...master). Esp. restic v0.14.0. Do you consider resticker + restic v0.14.0 to be stable?

**Comment by djmaze** [comment]
As documented in the other issue, `latest` is now always built from the latest `master` branch. So it includes all merged pull requests but is not yet officially released.

The `pr-` tags are automatically built for each pull request. This makes it easier to test.

> There seem to be some [changes since v1.6.0](https://github.com/djmaze/resticker/compare/1.6.0...master). Esp. restic v0.14.0. Do you consider resticker + restic v0.14.0 to be stable?

Tbh, I only did a few tests but I am not using in production yet. I guess it still is safe to release.

I guess I should add a note about the tagging scheme to the readme and then cut a new release. So thanks for the reminder!
