### ISSUE TITLE
Unable to connect to backblazeb2 

### ISSUE THREAD

**Issue by Enissay** [djmaze/resticker#165]
I have an issue make backblazeb2 work.

Initialization via cli works fine:
```bash
# restic -r b2:enytest:/blah init
enter password for new repository: 
enter password again: 
created restic repository 98xxxxxx at b2:enytest:/blah

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

# restic -r b2:enytest:/blah key list
enter password for repository: 
repository 98xxxxxx opened successfully, password is correct
created new cache in /home/eny/.cache/restic
 ID        User     Host      Created
-------------------------------------------------
*exxxx  eny  blah  2023-05-20 02:09:12
-------------------------------------------------
```

I have setup the needed vars properly:
```
    RESTIC_REPOSITORY: b2:enytest:/blah
    RESTIC_PASSWORD: xxxxxxxxxx
    B2_ACCOUNT_ID: yyyyyyyyyyy
    B2_ACCOUNT_KEY: zzzzzzzzzz
```

Yet the container keeps failing:
```
Container started
05/20/2023 2:09:48 AM  Checking configured repository 'b2:enytest:/blah' ...
05/20/2023 2:10:48 AM  Fatal: unable to open repository at b2:enytest:/blah: context deadline exceeded
05/20/2023 2:10:48 AM  Could not access the configured repository. Trying to initialize (in case it has not been initialized yet) ...
```

What am I missing ?

**Comment by djmaze** [comment]
Do internet connections in your docker containers work? (E.g. `docker-compose run --rm backup curl -I https://s3.us-west-001.backblazeb2.com`)

**Comment by Enissay** [comment]
Hmm, good point, no there's no internet.
I have the resticker container wired to the same network many other containers are using, and they are working fine...
Any suggestion what could be wrong ? given I have many containers running on the same network and having internet!

**Comment by Enissay** [comment]
Okay, I finally used another network and it works fine.
I still have to figure our why it is not working on my initial network >_>
Anyhow, It was a false alert, thank you for the support @djmaze <3
