### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by dodgex** [djmaze/resticker#179]
Hey there,

I am currently revising my server setup including backups. As a part of that, I am considering replacing my custom backup cron container with resticker.

For that I would like to use a version with the current restic binary...

> It is recommended to pin to the latest patch version (e.g. 1.6.0)

...and not use `latest` to avoid any unexpected breaking of stuff when you update the `latest` tag.
Unfortunately the [`1.7.0`](https://github.com/djmaze/resticker/releases/tag/1.7.0) tag is 10 Months old and only having restic 0.15.x

**Comment by hacdias** [comment]
Ping @djmaze

**Comment by djmaze** [comment]
Sorry for the late response. I will do that in a bit.

**Comment by djmaze** [comment]
Done. See https://github.com/djmaze/resticker/releases/tag/1.7.1
