### ISSUE TITLE
.ssh files copied to wrong location

### ISSUE THREAD

**Issue by nerdlich** [djmaze/resticker#184]
When using SFTP with public key authentication, the provided .ssh directory is copied to the wrong location:

`cp -r "${SSH_CONFIG_PATH}" /root/.ssh`

This creates `.ssh` inside `/root/.ssh`

This line works instead:

`cp -r "${SSH_CONFIG_PATH}" /root/`

**Comment by ThomDietrich** [comment]
Refers to

https://github.com/djmaze/resticker/blob/854f21eef9f0d29a0bfd3ad4f54ed7fca31b3d87/entrypoint#L11-L14

There is a better ay to accomplish this:

```bash
cp -r "${SSH_CONFIG_PATH}/." /root/.ssh 
```

**Comment by djmaze** [comment]
Happily taking a PR :)
