### ISSUE TITLE
Question: Is it possible to add backup arguments to cron jobs?

### ISSUE THREAD

**Issue by zoispag** [djmaze/resticker#19]
I am using restiker to automate my backups. I want to exclude a few directories matching some rules.
Restic allows to [exclude items listed in a file](https://restic.readthedocs.io/en/latest/040_backup.html#excluding-files), by providing the `--exclude-file` argument for the backup command.

Is it possible to provide certain arguments in the backup command of the cron job?

**Comment by djmaze** [comment]
As it currently stands, you can prepend your custom parameters to the `RESTIC_BACKUP_SOURCES` variable. For example the following should work:

```bash
RESTIC_BACKUP_SOURCES="--exclude-file=/excludes /data"
```

As this is an unclean approach, we should probably add a separate variable for this in the next version.

**Comment by zoispag** [comment]
Nice workaround for now! Thanks for your response! Cheers!

**Comment by zoispag** [comment]
Shall we re-open, just not to forget to do this?

**Comment by djmaze** [comment]
Yes.

**Comment by zoispag** [comment]
@djmaze reminder to reopen and remove the tags.

**Comment by zoispag** [comment]
Up

**Comment by ThomDietrich** [comment]
I'm also interested in the feature The issue is quickly taken care of [here](https://github.com/djmaze/resticker/blob/630d1d2080b62b84068f39abef6e45ef56456275/backup#L32) plus the needed bit of documentation. Would you accept a PR?
