### ISSUE TITLE
Pre- and post-backup commands won't execute

### ISSUE THREAD

**Issue by dasBuero** [djmaze/resticker#20]
I use resticker to backup my docker volumes on a regular base so I need to stop and restart my docker containers. I wrote bash scripts and put their paths into the appropriate environmental variables.

Restic backups with built-in cron are working like expected but my bash scripts won't start before and after the backup process.

My docker run command is as follows:

```bash
docker run -d --name resticker-app-data-daily \
--network production \
--restart always \
-v /app-data/resticker/scripts/daily:/scripts \
-v /app-data:/data/daily/docker-data:ro \
-v /backup/app-data:/backup \
-v /var/run/docker.sock:/var/run/docker.sock \
-e BACKUP_CRON="0 30 4 * * *" \
-e RESTIC_BACKUP_SOURCES=/data/daily \
-e RESTIC_REPOSITORY=/backup \
-e RESTIC_PASSWORD=secret \
-e RESTIC_BACKUP_TAGS=app-data-daily \
-e RESTIC_FORGET_ARGS="--prune --tag app-data-daily --keep-daily 7 --keep-weekly 4 --keep-monthly 12" \
-e PRE_COMMANDS=/scripts/pre-backup \
-e POST_COMMANDS_SUCCESS=/scripts/post-backup-success \
-e POST_COMMANDS_FAILURE=/scripts/post-backup-failure \
-e POST_COMMANDS_EXIT=/scripts/post-backup-exit \
-e TZ=Europe/Berlin \
mazzolino/restic
```

I tried several workarounds like executing my scripts with `docker exec` manually but it seems that both `bash` and `docker-cli` are not installed in resticker container. After manually installing both my scripts worked with `docker exec` but not within your backup script.

Any suggestions?

BTW: Thank you for writing an otherwise good working restic wrapper!

**Comment by hosseinsalemi** [comment]
Same problem.

**Comment by dasBuero** [comment]
@hosseinsalemi I have resolved this issue. You have to pull the latest release with `mazolino/restic:1.1.1` because `latest` pulls a much older version.
