### ISSUE TITLE
rclone support

### ISSUE THREAD

**Issue by seertenedos** [djmaze/resticker#21]
Any chance you can show a full example of rclone support? I tried but i can't get it to work as i get 

```
 docker-compose up
Creating network "backupdownload_default" with the default driver
Creating backupdownload_app_1 ...
Creating backupdownload_app_1 ... done
Attaching to backupdownload_app_1
app_1  | Trying to initialize remote repository 'rclone:restic_backups:/Download' (in case it has not been initialized yet)
app_1  | Fatal: create repository at rclone:restic_backups:/Download failed: invalid backend
app_1  | If the repo is in a local directory, you need to add a `local:` prefix

```
i had a look in the image and could not find rclone anywhere. I thought it would be in /usr/local/bin but it is not.

**Comment by djmaze** [comment]
Well, you probably ran into this trap: https://github.com/djmaze/resticker/issues/24

Sorry for that, the `latest` image is currently being updated.
