### ISSUE TITLE
Allow prune to be on a different schedule

### ISSUE THREAD

**Issue by seertenedos** [djmaze/resticker#22]
I would love it if prune could be on a different schedule. I have some backups that i run at a higher frequency like every 15 minutes at times but really only want prune to happen once a day.  It would be ideal if i could set a different schedule for the prune or specify it to happen every X backups either option would work.

**Comment by djmaze** [comment]
That's a good idea. My current plan is to have backup and prune as separate commands. That is so in swarm mode they can be separate services, orchestrated by something like [swarm-cronjob](https://github.com/crazy-max/swarm-cronjob).

For standalone / docker-compose usage, we would just have a single `CRON` variable which just runs the command given to the current container (either backup or prune).

**Comment by zoispag** [comment]
👍

**Comment by azurefreecovid** [comment]
This would be useful as I'd like to use the ``restic check`` as well

**Comment by zoispag** [comment]
I am interested too on this. Can I help somehow @djmaze ?

**Comment by djmaze** [comment]
I can probably work on this in the next 7 days. As the swarm-cronjob approach is currently not feasible (at least for [global jobs](https://github.com/crazy-max/swarm-cronjob/issues/20) and we need a non-swarm solution as well, it probably makes sense to now separate into backup and prune containers with different schedules. I can have a stab at that.
