### ISSUE TITLE
high speed restore

### ISSUE THREAD

**Issue by seertenedos** [djmaze/resticker#23]
not exactly your issue but thought you may be interested and could be worth having a special image for it.

The fork below has a fix for the restore that tooks restores for me from not finishing for 2 hours to finishing in 5 minutes on slower connections.
[https://github.com/ifedorenko/restic/tree/out-of-order-restore-no-progress](https://github.com/ifedorenko/restic/tree/out-of-order-restore-no-progress)

conversation about the issue here
https://forum.restic.net/t/really-slow-restore-when-having-a-around-4k-very-small-files/2368/4

hopefully they merge it into master soon as for me the restic restore was useless for my needs

**Comment by djmaze** [comment]
@seertenedos Cool stuff, thanks for the information. 

As that currently is not a problem for me, I'd rather not maintain a separate image, but wait for your patch to get into an official release. Feel free to roll your own image for the time being though!
