### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by zoispag** [djmaze/resticker#26]
Do you consider exposing an endpoint to export Restic operations to Prometheus for monitoring?

**Comment by djmaze** [comment]
Does restic expose metrics? That would be interesting. 

This is not something I am going to implement myself, but feel free to create a PR and I'll have a look!

And.. sorry for the late answer. Lost track of my notifications somehow.

**Comment by zoispag** [comment]
No worries. In the meantime I implemented my own solution. Restic itself does not offer metrics, but there is a `--json` flag that I am using in conjunction with jq and I generate metrics, which are outputted in a file and parsed by nodeexporter.

Happy to discuss if you want further and work on a viable solution.

**Comment by djmaze** [comment]
Would be interesting to have something like that at a certain point. Do you have any snippets you can share?

**Comment by azurefreecovid** [comment]
@zoispag: I'd be interested in this snippet if you were willing to share it, as I'd like to implement something similar myself.

**Comment by zoispag** [comment]
Ah, I was planning to reply here and the new github notifications happened, so I felt overwhelmed, hit the archive all button and forgot to ever reply back. Sorry for the delay @djmaze and thanks for the reminder @azurefreecovid. 

I wrote about the procedure [in a gist](https://gist.github.com/zoispag/4cfdd5d8f82946261ebb451a0c04ecbd). Let me know if you have any questions.

**Comment by azurefreecovid** [comment]
Thank you very much I'll take a look and let you know how I go

**Comment by zoispag** [comment]
Keep

**Comment by ThomDietrich** [comment]
Does anyone know if there is a restic option or discussion around a restic feature to generate both the human readable as well as the json output stream?

Feels like this ticket and #35 could be pushed in the right direction if the two could be combined.

**Comment by varac** [comment]
For the record, [restic-robot](https://github.com/Southclaws/restic-robot) did implement [prometheus metrics](https://github.com/Southclaws/restic-robot/blob/master/metrics.go), unfortunatly it isn't active anymore.
