### ISSUE TITLE
Error when using restic with rclone

### ISSUE THREAD

**Issue by ghost** [djmaze/resticker#30]
Hi, I want to run restic with rclone in order to access my Google Drive. Here is my setup:
I have my `docker-compose.yml` and my `rclone.conf` in the same dir (`/home`). Here is what my `docker-compose.yml` file looks like:

```docker-compose
restic:
      image: mazzolino/restic:latest
      container_name: restic
      volumes:
          - ./rclone.conf:/root/.config/rclone/rclone.conf
          - /home:/data:ro
      environment:
          - BACKUP_CRON=*/5 * * * *
          - RESTIC_REPOSITORY=rclone:backup:backup
          - RESTIC_PASSWORD=password
      restart: unless-stopped
```
Then I run it doing `docker-compose up restic` and here is what I get:
```
Starting restic ... done
Attaching to restic
restic        | Trying to initialize remote repository 'rclone:backup:backup' (in case it has not been initialized yet)
restic        | rclone: 2020/04/13 15:35:27 Failed to save config after 10 tries: Failed to move previous config to backup location: rename /root/.config/rclone/rclone.conf /root/.config/rclone/rclone.conf.old: device or resource busy
restic        | Fatal: create repository at rclone:backup:backup failed: error talking HTTP to rclone: context canceled
restic        | 
restic        | new cron: */5 * * * *
```
At the first time I thought that it was due to the volumes but even when I remove the `- /home:/data:ro` volume, I still get the error message.

Thanks for your help !

**Comment by djmaze** [comment]
Well, it *is* due to the volume, but the other one. I don't know rclone but it seems it wants to rename the rconf.conf file in order to make a backup. It is not possible to move a file which has been mounted directly. For rclone to work, you need to not mount the config file itself but a surrounding directory.

Replace:

```yaml
          - ./rclone.conf:/root/.config/rclone/rclone.conf
```

with:

```yaml
          - ./rclone_config:/root/.config/rclone
```

You need to create the directory `./rclone_config` and move your config file in there. Then it should work.

**Comment by djmaze** [comment]
Closing for now as there was no further feedback.

**Comment by lindsaymarkward** [comment]
I had this same problem and it took a long time to figure out.
@djmaze - can I suggest you add this as either an example/comment in the docker-compose file provided or update the readme to provide an example there? 
That would have helped me.

**Comment by djmaze** [comment]
@lindsaymarkward I found a better solution. See #83
