### ISSUE TITLE
Add an option for logging

### ISSUE THREAD

**Issue by azurefreecovid** [djmaze/resticker#35]
It would be great if the container provided an option to log the output of backup jobs to file. 

With this handy addition, and the use of the, already existing ``POST_COMMANDS_SUCCESS``, ``POST_COMMANDS_FAILURE`` and ``POST_COMMANDS_EXIT`` we could attach the contents of the backup log to any notification service.

Thoughts??

**Comment by djmaze** [comment]
Are we talking about the complete output that is currently printed to stdout? You want to send the complete output to a notification service?

**Comment by azurefreecovid** [comment]
Yes please.

I'd also like the option to specify just the json output from Restic.

**Comment by djmaze** [comment]
Using a proper [Docker logging driver](https://docs.docker.com/config/containers/logging/configure/) is not an option?

**Comment by azurefreecovid** [comment]
I'm not sure it would (could be wrong, feel free to let me know if you think I might be). As I want to send the log output off as either an email or part of a HTTP post request (to something like Healthchecks or Grafana etc) whilst keeping the container running.

**Comment by dodedodo** [comment]
Wouldn't it be quite easy to simply `tee` to log to a file? 

e.g. append `| tee backup.log` to [backup#L53](https://github.com/djmaze/resticker/blob/master/backup#L53). Or even wrap the whole backup script in a subshell, and tack a `tee` on at the end. 

I tried injecting/hacking it in `RESTIC_BACKUP_ARGS` but it seems you properly escaped these arguments. 

If djmaze agrees with this, I'm more than happy to submit a pull. But I feel like I must be missing something..?
