### ISSUE TITLE
Halt if initialization fails

### ISSUE THREAD

**Issue by ThomDietrich** [djmaze/resticker#37]
Referring to the unconditional true here:

https://github.com/djmaze/resticker/blob/630d1d2080b62b84068f39abef6e45ef56456275/entrypoint#L6

Does it make sense to ignore an error at this first point where the existence of the endpoint is checked? How about adding a check whether a repository is accessible before anything else?

**Comment by djmaze** [comment]
Yes, this a weakness in the current implementation. If you know a clean way of checking for the existence of the repository beforehand, please go ahead. Note that we have to make this work for *every* repository type that restic supports, i.e. local, SFTP, REST server, S3 / Minio, OpenStack Swift, Backblaze B2, Azure Blob Storage, Google Cloud Storage and other types via. rclone.

**Comment by ThomDietrich** [comment]
Not so much from my experience but according to https://restic.readthedocs.io/en/stable/075_scripting.html the snapshots command is what should be used.

**Comment by djmaze** [comment]
Oh, interesting, I did not yet see that part of the documentation I suppose.

That seems indeed to be a cleaner approach. Might be interesting for the next release.
