### ISSUE TITLE
"syntax error: unexpected redirection" when using PRE_COMMANDS

### ISSUE THREAD

**Issue by nikkoura** [djmaze/resticker#4]
When setting the PRE_COMMANDS env variable, the backup scripts returns the following message:

`restic_1  | /usr/local/bin/backup: line 5: syntax error: unexpected redirection`

It seems that the `< <` construct is not understood by alpine's sh.
Switching to bash solves the problem.

**Comment by djmaze** [comment]
Should be fixed by #7.
