### ISSUE TITLE
Restic Prune Args

### ISSUE THREAD

**Issue by PhasecoreX** [djmaze/resticker#43]
I see there is a `RESTIC_BACKUP_ARGS` environment variable, could you also add a `RESTIC_PRUNE_ARGS` environment variable? I'd like to use it to have these arguments:
```
-o b2.connections=50 --cleanup-cache
```
Thank you!

**Comment by djmaze** [comment]
Oh, that probably makes sense.

I can do that in the near future. Alternatively, PRs are welcome!

**Comment by PhasecoreX** [comment]
Sorry, very new to PRs! I'll fix it soon!
