### ISSUE TITLE
Provided rclone does not work on arm64

### ISSUE THREAD

**Issue by mattkasa** [djmaze/resticker#50]
The rclone binary is x86_64 inside the arm64 image. It looks like the `Dockerfile` specifies amd64 for rclone regardless of whether the image being built is amd64 or arm64.

I started looking at fixing this, but given the way rclone is currently installed, I wasn't sure if changing the install method to use the upstream install script (https://rclone.org/install.sh) would be desirable or not. But if that approach is ok, I'm happy to open a PR.

**Comment by djmaze** [comment]
Good catch.. Mhh, using the install script is not cool. Is there a package repository or similar?

**Comment by mattkasa** [comment]
> Good catch.. Mhh, using the install script is not cool. Is there a package repository or similar?

There's precompiled binaries in the same location as the amd64 ones:

amd64: https://downloads.rclone.org/v1.52.2/rclone-v1.52.2-linux-amd64.zip
arm64: https://downloads.rclone.org/v1.52.2/rclone-v1.52.2-linux-arm64.zip

Is there a good way to retain the checksum verification using something like `${ARCH}`?

Otherwise, the other options include starting `FROM rclone/rclone:latest` since they build a multi-arch image based on alpine, or installing rclone from source using `go get -u -v github.com/rclone/rclone` inside a go builder image and add the binary to the resticker image from the builder image.

What do you think would be best?

**Comment by djmaze** [comment]
Sorry for the late response. I think I prefer the first option (retain the checksum verification). This could be solved by COPYing and RUNning a separate script which compares the checksum according to the current `${ARCH}`.
