### ISSUE TITLE
Locked repository: Unlock strategy

### ISSUE THREAD

**Issue by ThomDietrich** [djmaze/resticker#51]
Hey all,

I ran a few tests and provoked a condition in which my test repository got locked. Before I would unlock manually and carry on. After #47 this doesn't seem possible anymore:

```
docker-compose run --rm backup-docker-services unlock
Checking configured repository 'rest:http://xxx:yyy@restic.server.de:8000/services' ...
Fatal: unable to create lock in backend: repository is already locked exclusively by PID 40 on jarvis by root (UID 0, GID 0)
lock was created at 2020-08-10 16:58:30 (14m26.520623527s ago)
storage ID 196a1a3b
Could not access the configured repository. Trying to initialize (in case it has not been initialized yet) ...
Fatal: create repository at rest:http://xxx:yyy@restic.server.de:8000/services failed: Fatal: config file already exists

Initialization failed. Please check error messages above and check your configuration. Exiting.
```

How do we want to deal with this? Is it reasonable to assume that if a command is given by the user the repository checking logic should be skipped?

Best! Thomas

**Comment by djmaze** [comment]
Oh, I did not yet run into this because I am using `docker exec` all the time with my swarm-based approach.

Skipping initialization if any command is given sounds like a sensible approach to me. The `init` command can also just be called explicitely so there is no need to run the container _without a command_ beforehand. 

But if we change the behaviour, we should probably document that.

**Comment by bachya** [comment]
This still exists – not stale.

**Comment by djmaze** [comment]
Or maybe just skip the repository checking logic if exactly the `unlock` command is given. That could prevent other regressions here.

**Comment by escoand** [comment]
I've the same problem. Before I discovered this container I'd a self generated script with a unlock between backup and forget.

**Comment by djmaze** [comment]
If there are no objections, I will go and implement my last proposal.

**Comment by escoand** [comment]
I think the root cause of the problem should be solved upstream. I have/had the same problem with 2 different scripts. So for me this seems to be a wrong handling within restic.

**Comment by escoand** [comment]
When looking at the issues in restic repository you can see there are many of similar reports: https://github.com/restic/restic/issues?q=is%3Aissue+locked+is%3Aclosed

**Comment by ThomDietrich** [comment]
I agree that the locking mechanism in restic seems a bit wobbly. Also discussed in #60 

@djmaze I wanted to tackle this and other topics we discussed in a pull request. Sadly my life is a bit unpredictable these days (in a good way). The PR will come but please do not feel blocked by that!

Imho the checking logic I "improved" is not a good approach after all. My latest thinking is that
- the checks should be executed at startup and before every job
- the checks should not stop execution, except in reasonable cases
- checks should be skipped when the image is called with a command, like `init` or `unlock`

> Or maybe just skip the repository checking logic if exactly the unlock command is given. That could prevent other regressions here.

Agreed 👍

**Comment by djmaze** [comment]
@ThomDietrich  That sounds very reasonable. I like your comprehensive solution and I would be okay to wait for that. 

By the way, I just released 1.3.0, which includes the update to Restic 0.11.

**Comment by indiebrain** [comment]
Maybe a useful workaround for anyone else landing here, When I need to manually remove a lock from a repository I issue a one-off `docker-compose run` of my resticer service and overriding the container's entrypoint like so:

```sh
docker-compose run --entrypoint="bash -lc" --rm <service-name> "restic --no-lock unlock"
```

**Comment by ramsrib** [comment]
bash isn't available in the container when i tried.

```shell
docker run --env-file .env --rm -it --entrypoint="sh" mazzolino/restic
```

Inside the container, check and clear the locks.
```
>> restic --no-lock list locks

>> restic --no-lock unlock
```

**Comment by djmaze** [comment]
@ramsrib Do you have the latest image? `bash` is definitely in there..
