### ISSUE TITLE
Sending mail on post backup

### ISSUE THREAD

**Issue by e-belair** [djmaze/resticker#53]
Hi,
How are you doing to send mail on post backup?
I tried to use a script but the mail command does not exists on the container

**Comment by djmaze** [comment]
I propose you use a separate container for that, like [apprise-microservice](https://github.com/djmaze/apprise-microservice). See here for an example: https://github.com/djmaze/resticker/issues/29#issuecomment-609049901

**Comment by e-belair** [comment]
I've finally implemented a script that installs msmtp and send a mail containing the logs of the backup:
##### send-mail.sh
```bash
# Install msmtp if not exists
if ! command -v msmtp &> /dev/null
then
  apk add --update --no-cache msmtp
  ln -sf /usr/bin/msmtp /usr/sbin/sendmail
fi

DCLOGS=$(docker logs --since "10h" -t resticker)

echo -e "Subject: Restic backup $1\n\nLast 10 hours logs:\n${DCLOGS}\n" | msmtp "${DEST_MAIL}"
```
In my dc file I'm using it like this:
```
      POST_COMMANDS_SUCCESS: |-
        /scripts/send-mail.sh SUCCESS
      POST_COMMANDS_FAILURE: |-
        /scripts/send-mail.sh FAILURE
      DEST_MAIL: admin@domain.tld
```

I'll look into the notification service, may be interesting as global notification for all my apps
