### ISSUE TITLE
Backup Size

### ISSUE THREAD

**Issue by Kourgiantakis** [djmaze/resticker#55]
Hello,

this is a question, not really an ISSUE. I'm quite new to docker so please excuse my question if it's stupid.
The volume that I'm backing up is about 53mb. The snapshot in my bucket is about 300kb. The log doesn't show anything unusual.

Is this normal or is the backup not working properly

Thanks in advance.

**Comment by zoispag** [comment]
You would need to share some more information. 
Can you share how you run resticker?

**Comment by Kourgiantakis** [comment]
Hey, i run it with docker compose, this is my file:

restic:
    container_name: restic
    image: mazzolino/restic
    hostname: docker
    environment:
        BACKUP_CRON: "0 0 4 * * *"
        RESTIC_REPOSITORY: s3:https://xxxxxxxxxxxxxxxxxx
        RESTIC_PASSWORD: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
        RESTIC_BACKUP_SOURCES: /source
        RESTIC_FORGET_ARGS: --keep-daily 7 --keep-weekly 4
        AWS_ACCESS_KEY_ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        AWS_SECRET_ACCESS_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        RUN_ON_STARTUP: "true"
        RESTIC_BACKUP_ARGS: --tag octoprint
        
    volumes:
        - octoprint:/source/octoprint

**Comment by djmaze** [comment]
@Kourgiantakis As restic does deduplication of data, if the biggest part of that data is redundant, that could be possible.
