### ISSUE TITLE
Wrong image on docker hub

### ISSUE THREAD

**Issue by ymph** [djmaze/resticker#57]
Hello,

The latest docker hub image `mazzolino/restic` updated yesterday do not match the content of this repository.
Moreover, there has been no recent commits on this repository mandating an update of the docker hub image.

The image pushed on docker hub seems to match the content of the `djmaze/crystal-sync` repository.

**Comment by djmaze** [comment]
Woah, what an embarassment. Turns out I accidentally pushed to the wrong repository. Really sorry, I just triggered a new build so the image is now correct again.

Sorry for the mess and @ymph very good catch, thank you!
