### ISSUE TITLE
Restic v0.11.0

### ISSUE THREAD

**Issue by ThomDietrich** [djmaze/resticker#58]
https://github.com/restic/restic/releases/tag/v0.11.0

Hey all, 
this is a ticket to
1. upgrade the included restic version
2. go throught the changelog and discuss whether changes affect us or could be of further interest.

Let's discuss

**Comment by djmaze** [comment]
From a first look, I do not see any changes which could break resticker. Should be a smooth upgrade I guess.

We could think about supporting [the new `repository-file` option](https://github.com/restic/restic/issues/1458), but I am not sure if this is interesting for anyone.

**Comment by djmaze** [comment]
Done in #59
