### ISSUE TITLE
Resticker Loop

### ISSUE THREAD

**Issue by yololftw** [djmaze/resticker#60]
When I choose RUN_ON_STARTUP: "true", if something fails in the process of backup we are stuck in a loop.

Let's say a pre command fails, the restic service gets stuck in a loop of running backup on startup. I think the service should exit cleanly while removing any locks placed on the remote repository

**Comment by ThomDietrich** [comment]
Hey @yololftw,
If I understood you correctly you'd rather have the backup command fail gracefully as part of the project logic, instead of the hard termination of the docker container. I agree and this should be part of #42

**Comment by ThomDietrich** [comment]
One more thought: A loop with `RUN_ON_STARTUP: "true"` is a good thing. If a temporary problem exists an eventual backup is ensured. The other option is a permanent config error and in that case the restart of the docker container is a best practice and must be dealt with by the user. Finally, remember that `RUN_ON_STARTUP` is a non-default option.

> should exit cleanly while removing any locks

Careful with this one. Resticker can not automatically remove any lock that wasn't created by its session. It is the task of restic to remove a lock. If a wild lock blocks a repository I believe it must be the task of the user to evaluate the situation and manually force-unlock.

**Comment by yololftw** [comment]
Sorry for the lock comment, I meant remove locks for that session and not all locks, I do not know why it happened but the I was stuck in a restart loop and each backup was creating a lock on the repository and it was not being released, I manually went to my B2 storage and deleted the locks.

Now that I think back my compose file had Restart policy set to always, this might be the reason for the loop I experienced. Possibly one of my first attempts at setup failed and it created a lock that was not removed. And since I had restart policy set to always things just went south. Since I was new to Restick I assumed this was an issue with Restick/Resticker. But on further introspection I am at fault with the restart always command.

**Comment by ThomDietrich** [comment]
I wouldn't even say your restart always setting was wrong. A locked repository can happen in some situations and that should be dealt with. That is the responsibility of restic itself and might be supported by resticker and we should keep that in mind for future improvements.

> I manually went to my B2 storage and deleted the locks

The resticker image can be used to make this easier for you. See https://github.com/djmaze/resticker#advanced-usage
