### ISSUE TITLE
Restic v0.12.0

### ISSUE THREAD

**Issue by ThomDietrich** [djmaze/resticker#74]
https://github.com/restic/restic/releases/tag/v0.12.0

Hey all,
this is a ticket to

1. upgrade the included restic version
2. go throught the changelog and discuss whether changes affect us or could be of further interest.

Linked to https://github.com/djmaze/resticker/pull/73

Let's discuss

**Comment by ThomDietrich** [comment]
I would suggest to test what is described here: https://github.com/restic/restic/issues/2706#issuecomment-752182199

**Comment by ThomDietrich** [comment]
Seeing this ticket https://github.com/restic/restic/issues/2739 I wonder if using `--no-lock` should be added to any part of the logic (e.g. the initialization availability check)

**Comment by djmaze** [comment]
Thanks for these thoughts.

I am busy struggling to get the armv7 build running again. Not sure if we can release the update first and then implement your ideas in a minor release?

**Comment by ThomDietrich** [comment]
Agreed. The aspects are just ideas for improvement and no breaking changes.

Btw I feel it makes a lot of sense to get into a rhythm of always tracking new restic versions by creating an issue like this one. On another thought: I would like to engage with the restic community more. The ideal constellation would be to be the number 1 endorsed docker solution for restic. At this point it would also be easier to e.g. implement failure detection in cooperation with the restic core developers...

**Comment by svenfoo** [comment]
> I am busy struggling to get the armv7 build running again.

As a user of `resticker` on a Raspberry Pi I am quite interested in getting a build with `restic 0.12` for `aarch64`. Can I somehow support you in your struggles with the ARM builds?

**Comment by djmaze** [comment]
@svenfoo It is already in master and in the `latest` docker image. But I will also cut a new (semver) release soon.

**Comment by svenfoo** [comment]
> @svenfoo It is already in master and in the `latest` docker image.

Thanks for pointing that out, I got it up and running on the Raspberry Pi.
