### ISSUE TITLE
network_mode: host required for docker-compose?

### ISSUE THREAD

**Issue by lindsaymarkward** [djmaze/resticker#82]
Thank you for this project.
I struggled to get it working. In the end I found that rsync didn't work from inside the container because it couldn't resolve domain names.
`ping 8.8.8.8` worked, but `ping google.com` didn't.
I changed/added `network_mode: host` to my `docker-compose.yml` file and that fixed it.

1. Should that be necessary, or not?
2. If 1. is true, can you please add it to the sample compose file?

**Comment by djmaze** [comment]
No, that should not be necessary. Sounds like a DNS problem on that Docker instance.

I experience DNS problems every now and then with Docker when switching networks. Did you try restarting the Docker daemon?

**Comment by ThomDietrich** [comment]
Agree, this is a host/docker problem, not an issue with the resticker image.

**Comment by lindsaymarkward** [comment]
Thanks for the replies. I've tried again without `network_mode: host` after restarting the Raspberry Pi 4.
My logs show:
```
$ docker-compose logs restic
Attaching to restic
restic           | Checking configured repository 'rclone:onedrive:Backups/homeautomation' ...
restic           | rclone: 2021/03/26 22:32:56 DEBUG : rclone: Version "v1.54.0-DEV" starting with parameters ["rclone" "serve" "restic" "--stdio" "--b2-hard-delete" "onedrive:Backups/homeautomation"]
restic           | rclone: 2021/03/26 22:32:56 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
restic           | rclone: 2021/03/26 22:32:56 DEBUG : Creating backend with remote "onedrive:Backups/homeautomation"
restic           | rclone: 2021/03/26 22:32:56 DEBUG : One drive root 'Backups/homeautomation': Token expired but no uploads in progress - doing nothing
restic           | rclone: 2021/03/26 22:32:56 DEBUG : onedrive: Loaded invalid token from config file - ignoring
restic           | rclone: 2021/03/26 22:33:16 DEBUG : onedrive: Token refresh failed try 1/5: Post "https://login.microsoftonline.com/common/oauth2/v2.0/token": dial tcp: lookup login.microsoftonline.com on 127.0.0.11:53: read udp 127.0.0.1:37726->127.0.0.11:53: i/o timeout
```
Here's some more from the short time the container is alive when I `up` it:
```
$ docker exec -it restic sh  
/ # ping google.com
ping: bad address 'google.com'
/ # cat /etc/resolv.conf 
nameserver 127.0.0.11
options ndots:0
/ # ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=116 time=47.959 ms
```
Now, when I put `network_mode: host` back in my compose file, it works, and:
```
/ # ping google.com
PING google.com (142.250.66.238): 56 data bytes
64 bytes from 142.250.66.238: seq=0 ttl=116 time=50.830 ms
...
/ # cat /etc/resolv.conf 
# Generated by resolvconf
domain localdomain
nameserver 192.168.1.8
nameserver 192.168.1.22
```

So, if this shouldn't be necessary, do you have any ideas where I should be troubleshooting other than restarting?
Thanks.

**Comment by djmaze** [comment]
Does it work in other containers? E.g. does this work?

```bash
docker run -it --rm alpine ping www.google.com
```

**Comment by lindsaymarkward** [comment]
Yes, that worked.
```
$  docker run -it --rm alpine ping www.google.com   
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
6c1162af251f: Pull complete 
Digest: sha256:826f70e0ac33e99a72cf20fb0571245a8fee52d68cb26d8bc58e53bfa65dcdfa
Status: Downloaded newer image for alpine:latest
PING www.google.com (216.58.203.100): 56 data bytes
64 bytes from 216.58.203.100: seq=0 ttl=115 time=49.868 ms
64 bytes from 216.58.203.100: seq=1 ttl=115 time=49.467 ms
```

**Comment by lindsaymarkward** [comment]
Thanks for replying to my issue @djmaze . I posted that the command you asked about ran successfully, but I'm not sure what this indicates or what I should do. Can you update me please? Thanks.

**Comment by djmaze** [comment]
@lindsaymarkward I just realized from the non-working *resolv.conf* you posted that it has two nameservers configured in your local network. Are you sure that both of them are correct and they both do work? I imagine Docker is only trying to use one of them when running the container in non-host mode, which might explain this problem.

**Comment by lindsaymarkward** [comment]
The non-working resolv is the one with the 127 address.
The working one (when in host networking) does work. These two 192 IPs are my two Pi Hole instances.

**Comment by djmaze** [comment]
So.. Really not sure about this. Running other images via docker compose works?
