### ISSUE TITLE
Switch to using the provided binaries instead of building everything from source

### ISSUE THREAD

**Issue by djmaze** [djmaze/resticker#84]
Restic as well as Rclone provide binaries for all supported platforms.

**Comment by smainz** [comment]
I might be able to help with this one. 

What I would do:
 - Assume OS is Linux
 - get the machine architecture via `uname -m`
 - download the executable matching Linux and the detected architecture from github.
 - put the executables into `/usr/local/bin`

You lose the verification of the sha checksums for the executables. Checksums are published next to each build on github, but if you fake the DNS entry for https://github.com while building these checksums are useless.

**Comment by djmaze** [comment]
@smainz I don't quite get your argument concerning the checksums. My approach would be to hardcode the checksums for the latest version in the Dockerfile (as variables) so you can verify the downloaded binaries using those values. I think that would be worthwhile, in order to be sure the image – wherever and whenever it is built – contains the same correct binaries you initially intended to use.

**Comment by djmaze** [comment]
implemented in #86

**Comment by smainz** [comment]
I see your point. This means, we have to provide the checksms for each architecture in the Dockerfile, as these are different for the different executables.

**Comment by djmaze** [comment]
Yes, but I think it would be worth doing that (for the 3 architectures we support).

**Comment by smainz** [comment]
I will add that later today.

**Comment by djmaze** [comment]
Fixed in #86
