### ISSUE TITLE
Many docker containers + volumes; only want to back up specifics

### ISSUE THREAD

**Issue by ahgraber** [djmaze/resticker#85]
I have multiple docker containers running on a host; most have multiple volumes.  How would I go about setting only certain volumes to be backed up?  Do I have to create one restic container per volume?  Can `RESTIC_BACKUP_SOURCES` take multiple arguments?  If so, how?

Thanks!

**Comment by zoispag** [comment]
In the restic container, mount all your volumes inside the same directory: eg `/mnt` and set this directory as your backup source.

**Comment by djmaze** [comment]
Looks like we need a FAQ section for this kind of stuff.
