### ISSUE TITLE
Possible to read the volumes from the docker socket

### ISSUE THREAD

**Issue by Akruidenberg** [djmaze/resticker#92]
Is it possible to add the possibility to read the volumes from the docker socket? Bivac has this option and it looks really handy to have. No volume mounts are needed, only the socket must mounted. 
It would be really nice to have this feature with Resticker.

**Comment by djmaze** [comment]
Ha, interesting, I didn't know Bivac. So you want to backup only local docker volumes? So why not just backup `/var/lib/docker/volumes` then?

If you want to backup docker volumes with remote volumes: I implemented a very primitive service which makes them all available under `/mnt/docker-volumes` so you can just backup that directory as well: https://github.com/djmaze/docker-plugin-volume-mounter
